/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.tech247.leavemgt;

import java.awt.BorderLayout;
import java.util.List;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.OutlineView;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import systems.tech247.dbaccess.DataAccess;
import systems.tech247.hr.Employees;

/**
 *
 * @author Admin
 */
public class DueLeave extends javax.swing.JPanel implements ExplorerManager.Provider {

    ExplorerManager em = new ExplorerManager();
    
    /**
     * Creates new form DueLeave
     */
    public DueLeave() {
        initComponents();
        setLayout(new BorderLayout());
        OutlineView ov = new OutlineView("Overdue Leave");
        ov.addPropertyColumn("sCycleNumber", "Leave Cycle");
        ov.addPropertyColumn("sStart", "Start Date");
        ov.addPropertyColumn("sEnd", "End Date");
        
        ov.addPropertyColumn("holidays", "Worked Holidays Days");
        ov.addPropertyColumn("accumulated", "Accumulated Days");
        ov.addPropertyColumn("daysTaken", "Taken Days");
        ov.addPropertyColumn("balance", "Due Days");
        ov.getOutline().setRootVisible(false);
        add(ov);
        List<Employees> list = DataAccess.searchEmployees("SELECT e FROM Employees e WHERE e.isDisengaged= 0");
        em.setRootContext(new AbstractNode(Children.create(new FactoryLeaveCycle(list), true)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public ExplorerManager getExplorerManager() {
        return em;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
