/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.tech247.leavemgt;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.BeanTreeView;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.WindowManager;
import systems.tech247.util.MessageType;
import systems.tech247.util.NotifyUtil;
import systems.tech247.util.QueryEmployee;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//systems.tech247.leavemgt//LeaveApplications//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "LeaveApplicationsTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true, roles = {"leave"})
@ActionID(category = "Window", id = "systems.tech247.leavemgt.LeaveApplicationsTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_LeaveApplicationsAction",
        preferredID = "LeaveApplicationsTopComponent"
)
@Messages({
    "CTL_LeaveApplicationsAction=LeaveApplications",
    "CTL_LeaveApplicationsTopComponent=Employee Leaves & Applications",
    "HINT_LeaveApplicationsTopComponent=This is a LeaveApplications window"
})
public final class LeaveApplicationsTopComponent extends TopComponent implements ExplorerManager.Provider {
    
    Boolean disengaged = false;
    String searchString = "";
    QueryEmployee query = new QueryEmployee();
    ExplorerManager em = new ExplorerManager();
    public LeaveApplicationsTopComponent() {
        initComponents();
        setName(Bundle.CTL_LeaveApplicationsTopComponent());
        setToolTipText(Bundle.HINT_LeaveApplicationsTopComponent());
        jpView.setLayout(new BorderLayout());
        BeanTreeView btv = new BeanTreeView();
        btv.setRootVisible(false);
        jpView.add(btv);
        
        jtEmployee.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyPressed(KeyEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyReleased(KeyEvent e) {
                getTheStringAndReload();
            }
        });
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpView = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtEmployee = new javax.swing.JTextField();
        jcbDisengaged = new javax.swing.JCheckBox();

        jpView.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpViewLayout = new javax.swing.GroupLayout(jpView);
        jpView.setLayout(jpViewLayout);
        jpViewLayout.setHorizontalGroup(
            jpViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpViewLayout.setVerticalGroup(
            jpViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(LeaveApplicationsTopComponent.class, "LeaveApplicationsTopComponent.jLabel1.text")); // NOI18N

        jtEmployee.setText(org.openide.util.NbBundle.getMessage(LeaveApplicationsTopComponent.class, "LeaveApplicationsTopComponent.jtEmployee.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jcbDisengaged, org.openide.util.NbBundle.getMessage(LeaveApplicationsTopComponent.class, "LeaveApplicationsTopComponent.jcbDisengaged.text")); // NOI18N
        jcbDisengaged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDisengagedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbDisengaged)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbDisengaged))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbDisengagedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDisengagedActionPerformed
        disengaged = jcbDisengaged.isSelected();
        searchString = jtEmployee.getText();
        String sqlString = "SELECT e FROM Employees e WHERE (e.surName LIKE  '%"+searchString+"%' OR e.otherNames LIKE  '%"+searchString+"%' OR e.empCode LIKE  '%"+searchString+"%') AND e.isDisengaged =  '"+disengaged+"'  " ;
        query.setSqlString(sqlString);
        loadItems(query);   
    }//GEN-LAST:event_jcbDisengagedActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox jcbDisengaged;
    private javax.swing.JPanel jpView;
    private javax.swing.JTextField jtEmployee;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
       String sqlString = "SELECT e FROM Employees e WHERE e.surName LIKE  'Nothing'" ;
        query.setSqlString(sqlString);
        loadItems(query);
        //NotifyUtil.error("Error", "Error", false);
        //NotifyUtil.warn("Warning", "Warning", false);
        
        NotifyUtil.show("Employees' Overdue Leave", "Employees with Overdue Leave", MessageType.WARNING, new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               //Show Overdue Leave Panel
               TopComponent tc = WindowManager.getDefault().findTopComponent("LeaveDueTopComponent");
               DialogDisplayer.getDefault().notify(new NotifyDescriptor.Message(tc, NotifyDescriptor.PLAIN_MESSAGE));
           }
       }, false);
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
       return em;
    }
    
    void getTheStringAndReload(){
        searchString = jtEmployee.getText();
        String sqlString = "SELECT e FROM Employees e WHERE (e.surName LIKE  '%"+searchString+"%' OR e.otherNames LIKE  '%"+searchString+"%' OR e.empCode LIKE  '%"+searchString+"%') AND e.isDisengaged =  '"+disengaged+"'  " ;
        
            query.setSqlString(sqlString);
                loadItems(query);
            
        
    }
    void loadItems(QueryEmployee query){
        em.setRootContext(new AbstractNode(Children.create(new FactoryEmployeesList(query), true)));
    }
}
