/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.tech247.leavemgt;

import java.awt.BorderLayout;
import java.util.List;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.OutlineView;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import systems.tech247.dbaccess.DataAccess;
import systems.tech247.hr.Employees;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//systems.tech247.leavemgt//LeaveDue//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "LeaveDueTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "systems.tech247.leavemgt.LeaveDueTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_LeaveDueAction",
        preferredID = "LeaveDueTopComponent"
)
@Messages({
    "CTL_LeaveDueAction=LeaveDue",
    "CTL_LeaveDueTopComponent=LeaveDue Window",
    "HINT_LeaveDueTopComponent=This is a LeaveDue window"
})
public final class LeaveDueTopComponent extends TopComponent implements ExplorerManager.Provider {
    ExplorerManager em = new ExplorerManager();
    public LeaveDueTopComponent() {
        initComponents();
        setName(Bundle.CTL_LeaveDueTopComponent());
        setToolTipText(Bundle.HINT_LeaveDueTopComponent());
        
        setLayout(new BorderLayout());
        OutlineView ov = new OutlineView("Overdue Leave");
        ov.addPropertyColumn("sCycleNumber", "Leave Cycle");
        ov.addPropertyColumn("sStart", "Start Date");
        ov.addPropertyColumn("sEnd", "End Date");
        
        
        ov.addPropertyColumn("accumulated", "Accumulated Days");
        ov.addPropertyColumn("daysTaken", "Taken Days");
        ov.addPropertyColumn("balance", "Due Days");
        ov.getOutline().setRootVisible(false);
        add(ov);
        List<Employees> list = DataAccess.searchEmployees("SELECT e FROM Employees e WHERE e.isDisengaged= 0");
        em.setRootContext(new AbstractNode(Children.create(new FactoryLeaveCycle(list), true)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
       return em;
    }
}
