/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.tech247.leavemgt;

import java.awt.BorderLayout;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.OutlineView;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import org.openide.util.lookup.ProxyLookup;
import systems.tech247.hr.Employees;
import systems.tech247.util.CapCreatable;
import systems.tech247.util.QueryEmployee;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//systems.tech247.leavemgt//LeaveApplications//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "LeaveApplicationsTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true, roles = {"leave"})
@ActionID(category = "Window", id = "systems.tech247.leavemgt.LeaveApplicationsTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_LeaveApplicationsAction",
        preferredID = "LeaveApplicationsTopComponent"
)
@Messages({
    "CTL_LeaveApplicationsAction=LeaveApplications",
    "CTL_LeaveApplicationsTopComponent=Employee Leaves & Applications",
    "HINT_LeaveApplicationsTopComponent=This is a LeaveApplications window"
})
public final class LeaveApplicationsTopComponent extends TopComponent implements ExplorerManager.Provider {
    
    Boolean disengaged = false;
    String searchString = "";
    QueryEmployee query = new QueryEmployee();
    ExplorerManager em = new ExplorerManager();
    Employees emp;
    InstanceContent content = new InstanceContent();
    Lookup lkp = new AbstractLookup(content);
    
    public LeaveApplicationsTopComponent(){
        this(null);
    }
    
    public LeaveApplicationsTopComponent(final Employees emp) {
        initComponents();
        setName(Bundle.CTL_LeaveApplicationsTopComponent());
        setToolTipText(Bundle.HINT_LeaveApplicationsTopComponent());
        setLayout(new BorderLayout());
        
        this.emp = emp;
        
        content.add(new CapCreatable() {
            @Override
            public void create() {
                TopComponent tc = new LeaveApplicationEditorTopComponent(emp);
                tc.open();
                tc.requestActive();
            }
        });
        OutlineView ov = new OutlineView("Leave Applications");
        ov.getOutline().setRootVisible(false);
        add(ov);
        
        ov.addPropertyColumn("from", "From");
        ov.addPropertyColumn("to", "To");
        ov.addPropertyColumn("days", "# Of Days");
        ov.addPropertyColumn("resume", "Resume Date");
        ov.addPropertyColumn("isCancelled", "Cancelled");
        ov.addPropertyColumn("remarks", "Remarks");
        
        associateLookup(new ProxyLookup(ExplorerUtils.createLookup(em, getActionMap()),lkp));
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        em.setRootContext(new AbstractNode(Children.create(new FactoryEmployeeLeaveApplications(emp), true)));
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
       return em;
    }
    
    
    
}
